apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: base
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      protocol: TCP
      name: http
  selector:
    app: app

